create database `nostalgia`;
use nostalgia;
CREATE TABLE `rollnodetails` (
  `rollNo` varchar(50) NOT NULL,
  `studentName` varchar(50) NOT NULL,
  `Department` varchar(50) NOT NULL,
  `Gender` varchar(1) NOT NULL,
  PRIMARY KEY (`rollNo`),
  UNIQUE KEY `rollNo_UNIQUE` (`rollNo`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `nominations` (
  `rollno` varchar(10) NOT NULL,
  `Mr.Handsome` varchar(45) DEFAULT NULL,
  `Ms.Beautiful` varchar(45) DEFAULT NULL,
  `Mr.Popular` varchar(45) DEFAULT NULL,
  `Ms.Popular` varchar(45) DEFAULT NULL,
  `Mr.Flirt` varchar(45) DEFAULT NULL,
  `Ms.Flirt` varchar(45) DEFAULT NULL,
  `Mr.Casanova` varchar(45) DEFAULT NULL,
  `Ms.Trendy` varchar(45) DEFAULT NULL,
  `Mr.Kanjoos` varchar(45) DEFAULT NULL,
  `Ms.Kanjoos` varchar(45) DEFAULT NULL,
  `Mr.Atti` varchar(45) DEFAULT NULL,
  `Ms.Atti` varchar(45) DEFAULT NULL,
  `Mr.Sportsperson` varchar(45) DEFAULT NULL,
  `Ms.Sportsperson` varchar(45) DEFAULT NULL,
  `Mr.Fundoo` varchar(45) DEFAULT NULL,
  `Ms.Fundoo` varchar(45) DEFAULT NULL,
  `Mr.Chaat` varchar(45) DEFAULT NULL,
  `Ms.Chaat` varchar(45) DEFAULT NULL,
  `Mr.Magicmoments` varchar(45) DEFAULT NULL,
  `Ms.Magicmoments` varchar(45) DEFAULT NULL,
  `Silencer` varchar(45) DEFAULT NULL,
  `Good Samaritan` varchar(45) DEFAULT NULL,
  `Jack of All trades` varchar(45) DEFAULT NULL,
  `Workaholic` varchar(45) DEFAULT NULL,
  `GPL` varchar(45) DEFAULT NULL,
  `Lost Puppy` varchar(45) DEFAULT NULL,
  `The Foodie` varchar(45) DEFAULT NULL,
  `Night Watchman` varchar(45) DEFAULT NULL,
  `Stalker` varchar(45) DEFAULT NULL,
  `Transformer` varchar(45) DEFAULT NULL,
  `Complaint Box` varchar(45) DEFAULT NULL,
  `Just Friends_1` varchar(45) DEFAULT NULL,
  `Just Friends_2` varchar(45) DEFAULT NULL,
  `Best Couple_1` varchar(45) DEFAULT NULL,
  `Best Couple_2` varchar(45) DEFAULT NULL,
  `Section 377_1` varchar(45) DEFAULT NULL,
  `Section 377_2` varchar(45) DEFAULT NULL,
  `101% Attendence` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`rollno`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `nostalgia`.`admin` (
  `settings` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`settings`));
CREATE TABLE `voting` (
  `rollno` varchar(10) NOT NULL,
  `Mr.Handsome` varchar(45) DEFAULT NULL,
  `Ms.Beautiful` varchar(45) DEFAULT NULL,
  `Mr.Popular` varchar(45) DEFAULT NULL,
  `Ms.Popular` varchar(45) DEFAULT NULL,
  `Mr.Flirt` varchar(45) DEFAULT NULL,
  `Ms.Flirt` varchar(45) DEFAULT NULL,
  `Mr.Casanova` varchar(45) DEFAULT NULL,
  `Ms.Trendy` varchar(45) DEFAULT NULL,
  `Mr.Kanjoos` varchar(45) DEFAULT NULL,
  `Ms.Kanjoos` varchar(45) DEFAULT NULL,
  `Mr.Atti` varchar(45) DEFAULT NULL,
  `Ms.Atti` varchar(45) DEFAULT NULL,
  `Mr.Sportsperson` varchar(45) DEFAULT NULL,
  `Ms.Sportsperson` varchar(45) DEFAULT NULL,
  `Mr.Fundoo` varchar(45) DEFAULT NULL,
  `Ms.Fundoo` varchar(45) DEFAULT NULL,
  `Mr.Chaat` varchar(45) DEFAULT NULL,
  `Ms.Chaat` varchar(45) DEFAULT NULL,
  `Mr.Magicmoments` varchar(45) DEFAULT NULL,
  `Ms.Magicmoments` varchar(45) DEFAULT NULL,
  `Silencer` varchar(45) DEFAULT NULL,
  `Good Samaritan` varchar(45) DEFAULT NULL,
  `Jack of All trades` varchar(45) DEFAULT NULL,
  `Workaholic` varchar(45) DEFAULT NULL,
  `GPL` varchar(45) DEFAULT NULL,
  `Lost Puppy` varchar(45) DEFAULT NULL,
  `The Foodie` varchar(45) DEFAULT NULL,
  `Night Watchman` varchar(45) DEFAULT NULL,
  `Stalker` varchar(45) DEFAULT NULL,
  `Transformer` varchar(45) DEFAULT NULL,
  `Complaint Box` varchar(45) DEFAULT NULL,
  `Just Friends` varchar(45) DEFAULT NULL,
  `Best Couple` varchar(45) DEFAULT NULL,
  `Section 377` varchar(45) DEFAULT NULL,
  `101% Attendence` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`rollno`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `candidates` (
  `rollno` varchar(10) NOT NULL,
  `Mr.Handsome` varchar(45) DEFAULT NULL,
  `Ms.Beautiful` varchar(45) DEFAULT NULL,
  `Mr.Popular` varchar(45) DEFAULT NULL,
  `Ms.Popular` varchar(45) DEFAULT NULL,
  `Mr.Flirt` varchar(45) DEFAULT NULL,
  `Ms.Flirt` varchar(45) DEFAULT NULL,
  `Mr.Casanova` varchar(45) DEFAULT NULL,
  `Ms.Trendy` varchar(45) DEFAULT NULL,
  `Mr.Kanjoos` varchar(45) DEFAULT NULL,
  `Ms.Kanjoos` varchar(45) DEFAULT NULL,
  `Mr.Atti` varchar(45) DEFAULT NULL,
  `Ms.Atti` varchar(45) DEFAULT NULL,
  `Mr.Sportsperson` varchar(45) DEFAULT NULL,
  `Ms.Sportsperson` varchar(45) DEFAULT NULL,
  `Mr.Fundoo` varchar(45) DEFAULT NULL,
  `Ms.Fundoo` varchar(45) DEFAULT NULL,
  `Mr.Chaat` varchar(45) DEFAULT NULL,
  `Ms.Chaat` varchar(45) DEFAULT NULL,
  `Mr.Magicmoments` varchar(45) DEFAULT NULL,
  `Ms.Magicmoments` varchar(45) DEFAULT NULL,
  `Silencer` varchar(45) DEFAULT NULL,
  `Good Samaritan` varchar(45) DEFAULT NULL,
  `Jack of All trades` varchar(45) DEFAULT NULL,
  `Workaholic` varchar(45) DEFAULT NULL,
  `GPL` varchar(45) DEFAULT NULL,
  `Lost Puppy` varchar(45) DEFAULT NULL,
  `The Foodie` varchar(45) DEFAULT NULL,
  `Night Watchman` varchar(45) DEFAULT NULL,
  `Stalker` varchar(45) DEFAULT NULL,
  `Transformer` varchar(45) DEFAULT NULL,
  `Complaint Box` varchar(45) DEFAULT NULL,
  `Just Friends` varchar(45) DEFAULT NULL,
  `Best Couple` varchar(45) DEFAULT NULL,
  `Section 377` varchar(45) DEFAULT NULL,
  `101% Attendence` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`rollno`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
